### ISSUE TITLE
Text mode used name not url

### ISSUE THREAD

**Issue by cderv** [gesquive/slate#1]
Hi, 

`README` says that 

> url: the url href, also used for text when no img is specified

However, it is the `name` field in the YAML that is used, `url`. In `partial/tile_slate.html`, it `.Link.name` as seen below

```html
{{ if .Link.img }}<img class="logo" src="{{ .Link.img }}"></img>{{ else }}{{ .Link.name }}{{ end }}</div>
```
I think it is a good choice to have name used rather than url. We should update the readme.

**Comment by cderv** [comment]
It seems to be different behavior on different navigator (IE, firefox). Something to do with the `slate.js` script. Will continue to try understand how it works.

**Comment by gesquive** [comment]
The site works like this:
- If javascript is disabled on the client browser, the `name` value is placed in the tile as a backup.
- If javascript is enabled, then the slate.js script will use the `data-url` attribute of the tile and make it look pretty by breaking apart the domain and arranging it around the tile.

I will add a note to the documentation about the `name` value acting as a backup.

**Comment by cderv** [comment]
Ok I see. I think it could be a good idea to add that in the documentation. 

However, f javascript is disabled on the client browser, `name` value is used but we can't change background and text color by the `link.yaml` as these variable are used by `slate.js` only right ?

**Comment by gesquive** [comment]
Correct, without javascript, most of the attributes will not work, but at least you'll be able to identify and click on the tiles.
